<h1>Cadastro de Clientes</h1>
<hr>

<form method="post" action="Request.php?class=ClientCtr&method=run">
    <!-- input hiddent to store the ID -->
    <input type="hidden" name="id" value="<?=$this->model->getId()?>">
    <label for="name">Nome:</label>
    <input type="text" name="name" id="name" value="<?=$this->model->getName()?>"> <br>
    <label for="birthday">Data Nascto:</label>
    <input type="date" name="birthDate" id="birthDate" value="<?=$this->model->getBirthDate()?>"> <br>
    <label for="gender">Sexo:</label>
    <select name="gender" id="gender">
        <option value="M" <?=$this->model->getGender() == 'M' ? 'selected' : ''?>>Masculino</option>
        <option value="F" <?=$this->model->getGender() == 'F' ? 'selected' : ''?>>Feminino</option>
    </select> <br>
    <!-- command buttons -->
    <input type="submit" name="command" value="Novo">
    <input type="submit" name="command" value="Salvar">
    <input type="submit" name="command" value="Excluir">

</form>
