<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Título aqui!</title>
</head>
<body>
    <div id="container">
        <header>
            <h1>Exemplo MVC</h1>
        </header>
        <nav>
            <a href="index.php">Início</a>
            <a href="#">Link 01</a>
            <a href="#">Link 02</a>
        </nav>
        <section id="content">
        
        